title:        Drupal Hook
tagline:      'A drupal related blog'
description:  'An elegant Drupal Blog'
url:          http://drupalhook.tumblr.com
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     20
